
import ceo from '../assets/images/profile/Ceo.jpg';
import admin from '../assets/images/profile/admin.jpg';
import team from '../assets/images/profile/team.jpg';
import executive from '../assets/images/profile/service_executive.jpg';
import type { TeamMember } from './admintypes';

export const admindummydata: TeamMember[] = [
  {
    id: 'TM001',
    name: 'Sherman oberoi',
    email: 'serman@vistora.com',
    mobile: '+91 98765 43210',
    profile_image: ceo,
    role: 'superadmin',
    joined_date: '2023-01-10',
    last_active: '2025-06-30T14:20:00Z',
    status: 'Active',
    dashboard_access : 'admin',
    skills: ['React', 'Node.js'],
    permissions: {
      full_access: true,
      can_manage_users: true,
      can_manage_orders: true,
      can_manage_products: true,
      can_manage_finances: true,
      can_manage_roles: true,
    },
    activity_logs: [
      { action: 'Logged in', timestamp: '2025-06-30T14:20:00Z', ip: '192.168.0.1' },
      { action: 'Updated user roles', timestamp: '2025-06-28T11:05:00Z', ip: '192.168.0.1' },
    ],
    security: {
      two_factor_enabled: true,
      last_password_change: '2025-01-15',
      login_devices: ['Chrome on Mac', 'Safari on iPhone'],
    },
    region: 'India',
    timezone: 'Asia/Kolkata',
    language: 'English',
  },
  {
    id: 'TM002',
    name: 'Srinidhi Sethi',
    email: 'srinidhi@vistora.com',
    mobile: '+91 99888 77665',
    profile_image: admin,
    role: 'admin',
    joined_date: '2023-06-01',
    last_active: '2025-06-29T10:10:00Z',
    status: 'Active',
    skills: ['React', 'Node.js'],
    dashboard_access : 'admin',
    permissions: {
      full_access: false,
      can_manage_users: true,
      can_manage_orders: true,
      can_manage_products: true,
      can_manage_finances: false,
      can_manage_roles: false,
    },
    activity_logs: [
      { action: 'Added new product', timestamp: '2025-06-25T09:45:00Z', ip: '192.168.0.4' },
      { action: 'Handled return request', timestamp: '2025-06-24T13:30:00Z', ip: '192.168.0.4' },
    ],
    security: {
      two_factor_enabled: true,
      last_password_change: '2024-12-01',
      login_devices: ['Edge on Windows', 'Android App'],
    },
    region: 'India',
    timezone: 'Asia/Kolkata',
    language: 'English',
  },
  {
    id: 'TM003',
    name: 'Ashish Jain',
    email: 'ashish@vistora.com',
    mobile: '+1 415 555 0198',
    profile_image: team,
    role: 'team',
    joined_date: '2024-02-15',
    last_active: '2025-06-30T16:00:00Z',
    status: 'Active',
    skills: ['React', 'Node.js'],
    dashboard_access : 'admin',
    permissions: {
      full_access: false,
      can_manage_users: false,
      can_manage_orders: true,
      can_manage_products: false,
      can_manage_finances: false,
      can_manage_roles: false,
    },
    activity_logs: [
      { action: 'Updated order status', timestamp: '2025-06-30T15:55:00Z', ip: '10.0.0.3' },
    ],
    security: {
      two_factor_enabled: false,
      last_password_change: '2024-05-10',
      login_devices: ['Firefox on Linux'],
    },
    region: 'USA',
    timezone: 'America/Los_Angeles',
    language: 'English',
  },
  {
    id: 'TM004',
    name: 'Shradha Kulkarni',
    email: 'shradha@vistora.com',
    mobile: '+91 88000 11223',
    profile_image: executive,
    role: 'serviceexecutive',
    joined_date: '2024-06-01',
    last_active: '2025-06-29T09:20:00Z',
    status: 'Inactive',
    skills: ['React', 'Node.js'],
    dashboard_access : 'service',
    permissions: {
      full_access: false,
      can_manage_users: false,
      can_manage_orders: true,
      can_manage_products: false,
      can_manage_finances: false,
      can_manage_roles: false,
    },
    activity_logs: [],
    security: {
      two_factor_enabled: false,
      last_password_change: '2025-04-01',
      login_devices: ['Chrome on Android'],
    },
    region: 'India',
    timezone: 'Asia/Kolkata',
    language: 'English',
  },
];
